# Generated by Django 5.0.3 on 2024-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carname', models.CharField(max_length=150)),
                ('Fueltype', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=500)),
                ('img', models.ImageField(default='', upload_to='')),
                ('phone', models.CharField(max_length=15)),
                ('Date', models.DateField(null=True)),
                ('Details', models.CharField(max_length=1000)),
            ],
        ),
    ]
