# Generated by Django 5.0.3 on 2024-05-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
