# Generated by Django 5.0.3 on 2024-05-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdetails',
        ),
    ]
