# Generated by Django 5.0.3 on 2024-05-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userregister',
        ),
    ]
