# Generated by Django 5.0.3 on 2024-05-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_delete_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderdetails',
        ),
    ]
