# Generated by Django 5.0.3 on 2024-05-08 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_delete_orderdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('phone', models.IntegerField(null=True)),
                ('DrivingLicene', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='')),
                ('Address', models.CharField(max_length=500)),
                ('Bookingdate', models.DateTimeField(null=True)),
                ('Returndate', models.DateTimeField(null=True)),
                ('Bookinglocation', models.CharField(max_length=255)),
                ('Destinationlocation', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=35)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField(null=True)),
                ('Country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fueltype', models.CharField(max_length=50)),
                ('carname', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('carimage', models.ImageField(default='', upload_to='')),
                ('customerdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.customerdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
