# Generated by Django 5.0.3 on 2024-05-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_customerdetails_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
