# Generated by Django 5.0.3 on 2024-05-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='carname',
            new_name='carid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Bookingdate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Fueltype',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Returndate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='carimage',
        ),
    ]
