# Generated by Django 5.0.3 on 2024-05-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_remove_customerdetails_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
